version: '3'

services:
  maildev:
    # Can be access in browser at localhost:1080.
    # Signin mail can be show at this adress.
    # Server is accessible at localhost:1025, using app.env default config.
    image: maildev/maildev
    ports:
      - '1080:1080'
      - '${MAILDEV_PORT}:1025'
  base-api:
    extends:
      file: docker-compose.app.yml
      service: base-api
    depends_on:
      - qdrant
      - pgdb
      - redis
      - minio

  qdrant:
    image: qdrant/qdrant:v1.6.1
    mem_limit: 450m
    ports:
      - '127.0.0.1:${QDRANT_PORT}:6333'
    volumes:
      - ./data/qdrant_storage:/qdrant/storage

  pgdb:
    image: postgres:15
    restart: unless-stopped
    volumes:
      - type: volume
        source: pgdb-data
        target: '/var/lib/postgresql/data'
    ports:
      - '127.0.0.1:${DBPORT}:5432'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ${DBUSER}
      POSTGRES_PASSWORD: ${DBPASS}

  # # https://gist.github.com/kincaidoneil/bc2516111f0ec8850cd6020b8191b27b
  # supavisor:
  #   image: supabase/supavisor:1.1.39
  #   restart: unless-stopped
  #   ports:
  #     - 4000:4000
  #     - 5432:5432
  #   environment:
  #     # POSTGRES_DB: postgres
  #     # POSTGRES_USER: ${DBUSER}
  #     # POSTGRES_PASSWORD: ${DBPASS}
  #     PORT: '4000'
  #     PROXY_PORT_SESSION: '5432'
  #     PROXY_PORT_TRANSACTION: '6543'
  #     DATABASE_URL: 'postgresql://admin:password@pgdb:5432/funfun-ai'
  #     SECRET_KEY_BASE: SECRET
  #     VAULT_ENC_KEY: '12345678901234567890123456789032'
  #     API_JWT_SECRET: 'dev'
  #     REGION: 'local'
  #     ERL_AFLAGS: ' -proto_dist inet_tcp'
  #   command: sh -c "/app/bin/migrate && /app/bin/server"
  #   depends_on:
  #     - pgdb

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
      PGADMIN_LISTEN_PORT: 5050
    volumes:
      - type: volume
        source: pgadmin-data
        target: /root/.pgadmin
    restart: unless-stopped
    ports:
      - '127.0.0.1:${PGADMIN_PORT}:5050'

  redis:
    image: 'redis:6'
    user: '999:999'
    # command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - '127.0.0.1:${REDIS_PORT}:6379'
    volumes:
      - redis-data:/data
      - redis-conf:/usr/local/etc/redis/redis.conf

  redis-ui:
    image: patrikx3/p3x-redis-ui:latest
    depends_on:
      - redis
    ports:
      - 127.0.0.1:${REDIS_UI_PORT}:7843
    volumes:
      - p3x-redis-ui-settings:/settings

  # Use minio to mock s3
  minio:
    image: 'minio/minio:latest'
    ports:
      - '9000:9000'
      - '9090:9090'
    environment:
      MINIO_ROOT_USER: 'root'
      MINIO_ROOT_PASSWORD: 'password'
    volumes:
      - 'minio:/data/minio'
    command: minio server /data/minio --console-address ":9090"
volumes:
  pgdb-data:
  pgadmin-data:
  redis-data:
  redis-conf:
  p3x-redis-ui-settings:
  minio:
  node_modules:
